--------------------------------------------------------------------------------
-- Configurable options
--------------------------------------------------------------------------------

---@class DieShrink.OptionDefinition
---@field type string The type of the option, which determines how the option is rendered in the UI and how user input is processed. Required.
---@field key? string Unique string key for this definition within an IC, generated by the compiler. Not used within the editor.

---@class DieShrink.InputOptionDefinition : DieShrink.OptionDefinition
---@field type "input"
---@field min? int Minimum value the user can enter for the option.
---@field max? int Maximum value the user can enter for the option.
---@field default? int Default value for the option if the user blanks the field.
---@field signal? SignalID The signal that will be sent into the IC with the value of the option.

---@class DieShrink.OptionChoice
---@field key string The key of the option for which the choice applies.

---@class DieShrink.InputOptionChoice : DieShrink.OptionChoice
---@field value int The chosen value.
