--------------------------------------------------------------------------------
-- Configurable options
--------------------------------------------------------------------------------

local sig_lib = require("lib.core.signal")
local strace = require("lib.core.strace")

---@class DieShrink.OptionDefinition
---@field type string The type of the option, which determines how the option is rendered in the UI and how user input is processed. Required.
---@field key? string Unique string key for this definition within an IC, generated by the compiler. Not used within the editor.
---@field label string Label for identifying the option when setting.

---@class DieShrink.InputOptionDefinition : DieShrink.OptionDefinition
---@field type "input"
---@field min? int Minimum value the user can enter for the option.
---@field max? int Maximum value the user can enter for the option.
---@field default? int Default value for the option if the user blanks the field.
---@field signal? SignalID The signal that will be sent into the IC with the value of the option.

---@class DieShrink.OptionChoice
---@field key string The key of the option for which the choice applies.

---@class DieShrink.InputOptionChoice : DieShrink.OptionChoice
---@field value int The chosen value.

---@alias DieShrink.OptionChoices {[string]: DieShrink.OptionChoice}

local lib = {}

---@param option_def DieShrink.InputOptionDefinition
---@param option_choice DieShrink.InputOptionChoice?
local function generate_input_control_behavior(option_def, option_choice)
	local signal = option_def.signal
	local value = option_choice and option_choice.value
	if not signal or not value then return nil end

	return sig_lib.compose_simple_ccbpcb({ signal }, nil, value)
end

---@param option_def DieShrink.OptionDefinition?
---@param option_choice DieShrink.OptionChoice?
---@return ConstantCombinatorBlueprintControlBehavior? control_behavior
function lib.generate_option_control_behavior(option_def, option_choice)
	if option_def and option_def.type == "input" then
		---@cast option_choice DieShrink.InputOptionChoice
		---@cast option_def DieShrink.InputOptionDefinition
		return generate_input_control_behavior(option_def, option_choice)
	end
end

---@param comb LuaEntity A constant combinator entity.
---@param cb LuaConstantCombinatorControlBehavior The combinator's control behavior.
---@param option_def DieShrink.InputOptionDefinition
---@param option_choice DieShrink.InputOptionChoice
local function apply_input_option(comb, cb, option_def, option_choice)
	local signal = option_def.signal
	local value = option_choice.value
	if not signal or not value then return end

	sig_lib.apply_simple_cccb(cb, { signal }, nil, value)
end

---@param comb LuaEntity? A constant combinator entity.
---@param option_def DieShrink.OptionDefinition?
---@param option_choice DieShrink.OptionChoice?
function lib.apply_option_to_combinator(comb, option_def, option_choice)
	if not comb or not comb.valid then return end
	local cb = comb.get_or_create_control_behavior() --[[@as LuaConstantCombinatorControlBehavior?]]
	if not cb then return end
	if option_def and option_def.type == "input" then
		---@cast option_def DieShrink.InputOptionDefinition
		---@cast option_choice DieShrink.InputOptionChoice
		apply_input_option(comb, cb, option_def, option_choice)
	end
end

return lib
