-- Invisible circuit entities generated by the circuit compiler.

local constants = require("lib.constants")
local tlib = require("lib.core.table")

---@type data.Sprite
local invisible_sprite = {
	filename = __GRAPHICS_PATH__ .. "invisible.png",
	width = 1,
	height = 1,
}

---@type data.ElectricEnergySource
local energy_source = {
	type = "electric",
	usage_priority = "secondary-input",
	render_no_network_icon = false,
	render_no_power_icon = false,
}

local TINY_BOX_SIZE = 0.0001
local ZERO_VECTOR = { 0, 0 }

---@type data.WireConnectionPoint
local ZERO_CONNECTION_POINT = {
	wire = { green = ZERO_VECTOR, red = ZERO_VECTOR },
	shadow = { green = ZERO_VECTOR, red = ZERO_VECTOR },
}

-- Base for invisible combinators
---@type data.CombinatorPrototype
local base_prototype = {
	-- PrototypeBase
	name = "DO_NOT_USE",
	type = "combinator",
	hidden_in_factoriopedia = true,

	-- EntityPrototype
	flags = {
		"placeable-off-grid",
		"not-on-map",
		"not-blueprintable",
		"not-deconstructable",
		"not-upgradable",
		"hide-alt-info",
	},
	collision_mask = { layers = {} },
	-- XXX: TYPES: FMTK vector type issue
	---@diagnostic disable-next-line: missing-fields
	collision_box = {
		{ -TINY_BOX_SIZE, -TINY_BOX_SIZE },
		{ TINY_BOX_SIZE, TINY_BOX_SIZE },
	},
	-- XXX: TYPES: FMTK vector type issue
	---@diagnostic disable-next-line: missing-fields
	selection_box = { { -0.01, -0.01 }, { 0.01, 0.01 } },
	minable = nil,
	selectable_in_game = false,
	allow_copy_paste = false,
	created_smoke = nil,

	-- CombinatorPrototype
	active_energy_usage = "1W",
	energy_source = energy_source,
	circuit_wire_max_distance = 64,
	draw_circuit_wires = false,
	draw_copper_wires = false,
	-- sprites = invisible_sprite,
	-- activity_led_sprites = invisible_sprite,
	activity_led_light_offsets = {
		ZERO_VECTOR,
		ZERO_VECTOR,
		ZERO_VECTOR,
		ZERO_VECTOR,
	},
	screen_light_offsets = {
		ZERO_VECTOR,
		ZERO_VECTOR,
		ZERO_VECTOR,
		ZERO_VECTOR,
	},
	-- Constant comb
	circuit_wire_connection_points = {
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
	},
	input_connection_points = {
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
	},
	output_connection_points = {
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
		ZERO_CONNECTION_POINT,
	},
	input_connection_bounding_box = {
		{ -TINY_BOX_SIZE, -TINY_BOX_SIZE },
		{ TINY_BOX_SIZE, TINY_BOX_SIZE },
	},
	output_connection_bounding_box = {
		{ -TINY_BOX_SIZE, -TINY_BOX_SIZE },
		{ TINY_BOX_SIZE, TINY_BOX_SIZE },
	},
}

---@type data.ConstantCombinatorPrototype
local constant_combinator = tlib.assign({}, base_prototype, {
	name = constants.mod_prefix .. "-constant-combinator",
	type = "constant-combinator",
})

---@type data.ArithmeticCombinatorPrototype
local arithmetic_combinator = tlib.assign({}, base_prototype, {
	name = constants.mod_prefix .. "-arithmetic-combinator",
	type = "arithmetic-combinator",
})

---@type data.DeciderCombinatorPrototype
local decider_combinator = tlib.assign({}, base_prototype, {
	name = constants.mod_prefix .. "-decider-combinator",
	type = "decider-combinator",
})

---@type data.SelectorCombinatorPrototype
local selector_combinator = tlib.assign({}, base_prototype, {
	name = constants.mod_prefix .. "-selector-combinator",
	type = "selector-combinator",
})

data:extend({
	constant_combinator,
	arithmetic_combinator,
	decider_combinator,
	selector_combinator,
})

-- Invisible container for internal pad connections
---@type data.ContainerPrototype
local pad_connector = {
	-- PrototypeBase
	type = "container",
	name = constants.mod_prefix .. "-pad-connector",
	hidden_in_factoriopedia = true,

	-- ContainerPrototype
	inventory_size = 0,
	circuit_wire_max_distance = constants.circuit_wire_max_distance,
	draw_copper_wires = false,
	draw_circuit_wires = false,

	-- EntityWithHealthPrototype
	max_health = 1,

	-- EntityPrototype
	flags = {
		"placeable-off-grid",
		"not-on-map",
		"not-blueprintable",
		"not-deconstructable",
		"not-upgradable",
		"hide-alt-info",
	},
	collision_mask = { layers = {} },
	-- XXX: TYPES: FMTK vector type issue
	---@diagnostic disable-next-line: missing-fields
	collision_box = {
		{ -TINY_BOX_SIZE, -TINY_BOX_SIZE },
		{ TINY_BOX_SIZE, TINY_BOX_SIZE },
	},
	-- XXX: TYPES: FMTK vector type issue
	---@diagnostic disable-next-line: missing-fields
	selection_box = { { -0.01, -0.01 }, { 0.01, 0.01 } },
	minable = nil,
	selectable_in_game = false,
	allow_copy_paste = false,
	created_smoke = nil,
}

data:extend({ pad_connector })
